# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ feature/** ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Download and install vscp-helper-lib
        run: |
          sudo wget https://github.com/grodansparadis/vscp-helper-lib/releases/download/v15.0.0/libvscphelper_15.0.0_amd64.deb
          sudo apt install ./libvscphelper_15.0.0_amd64.deb
          sudo ldconfig
          ls /usr/lib/x86_64-linux-gnu/libvscp*

      - name: Build logger (release)
        run: |
          cd ./logger
          make release
          cd ..

      - name: Build nodeSim (release)
        run: |
          cd ./nodeSim
          make release
          cd ..

      - name: Build programmer (release)
        run: |
          cd ./programmer
          make release
          cd ..
